name       : python-tensorflow-serving-api
version    : 2.6.2
release    : 7
source     :
    - https://github.com/tensorflow/serving/archive/refs/tags/2.6.2.tar.gz : 193d2cf959d9444a2837fe13f3efa51127532ad9ee99585903301c1a4a4c21c9
license    : Apache-2.0
component  : programming.python
summary    : A flexible, high-performance serving system for machine learning models
description: |
    TensorFlow Serving is an open-source software library for serving machine learning models. It deals with the inference aspect of machine learning, taking models after training and managing their lifetimes, providing clients with versioned access via a high-performance, reference-counted lookup table.
networking : yes
builddeps  :
    - bazel
    - git
    - numpy
    - python-wheel
    - python-setuptools
setup      : |
    sed -i '78s/python/python3/' tensorflow_serving/tools/pip_package/build_pip_package.sh
    sed -i "s|bazel-genfiles/|bazel-out/k8-opt/bin/|g" tensorflow_serving/tools/pip_package/build_pip_package.sh
build      : |
    bazel build //tensorflow_serving/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_serving*.whl
