name       : python-tensorflow-serving-api
version    : 1.14.0
release    : 3
source     :
    - https://github.com/tensorflow/serving/archive/1.14.0.tar.gz : a9ec3cec537b144da632d9d204ebc2f9016734abd39774c75ad911c718d225b5
license    : Apache-2.0
component  : programming.python
summary    : A flexible, high-performance serving system for machine learning models
description: |
    TensorFlow Serving is an open-source software library for serving machine learning models. It deals with the inference aspect of machine learning, taking models after training and managing their lifetimes, providing clients with versioned access via a high-performance, reference-counted lookup table.
networking : yes
builddeps  :
    - bazel
    - python-wheel
    - python-setuptools
setup      : |
    sed -i '78s/python/python3/' tensorflow_serving/tools/pip_package/build_pip_package.sh
build      : |
    bazel build //tensorflow_serving/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_serving*.whl
